package com.mkstore.mk.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class MkPlatformMenuExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by JoinPlugin
     * Name of the database table represented by this class
     */
    public static final String TABLE = "mk_platform_menu";

    /**
     * This field was generated by JoinPlugin
     * SQL query alias of the database table represented by this class
     */
    public static final String ALIAS = "mk_platform_menu";

    /**
     * This field was generated by JoinPlugin
     * SQL query alias of the database table represented by this class
     */
    public static final String ALIAS_ = "mk_platform_menu.";

    private List<String> from;

    private Integer limit;

    private Integer offset;

    public MkPlatformMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        from = null;
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public List<String> getFrom() {
        return from;
    }

    public MkPlatformMenuExample addFromClause(String join) {
        if (join == null || (join = join.trim()).length() == 0) return this;
        if (from == null) from = new java.util.ArrayList<String>();
        from.add(join);
        return this;
    }

    /**
     * @param formatString A {@link java.util.Formatter format string} for join expression
     * @param firstArg First argument referenced by the format specifiers in the format string
     * @param secondAndFurtherArgs Second and further arguments referenced by the format specifiers in the format string
     */
    public MkPlatformMenuExample addFromClause(String formatString, Object firstArg, Object ... secondAndFurtherArgs) {
        if (formatString == null || (formatString = formatString.trim()).length() == 0) return this;
        if (from == null) from = new java.util.ArrayList<String>();
        Object[] temp = new Object[(secondAndFurtherArgs == null ? 0 : secondAndFurtherArgs.length) + 1];
        if (secondAndFurtherArgs != null) System.arraycopy(secondAndFurtherArgs, 0, temp, 1, secondAndFurtherArgs.length);
        temp[0] = firstArg;
        String formatted = String.format(formatString, temp);
        from.add(formatted);
        return this;
    }

    public Integer getLimit() {
        return limit;
    }

    public Integer getOffset() {
        return offset;
    }

    public MkPlatformMenuExample setLimitAndOffset(Integer limit, Integer offset) {
        if (limit != null && limit > 0) {
            this.limit = limit;
            this.offset = (offset != null && offset > 0) ? offset : null;
        } else {
            this.limit = this.offset = null;
        }
        return this;
    }

    public MkPlatformMenuExample setLimit(Integer limit) {
        return setLimitAndOffset(limit, null);
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlatformMenuIdIsNull() {
            addCriterion("mk_platform_menu.platform_menu_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdIsNotNull() {
            addCriterion("mk_platform_menu.platform_menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdEqualTo(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id =", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdNotEqualTo(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id <>", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdGreaterThan(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id >", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id >=", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdLessThan(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id <", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_menu.platform_menu_id <=", value, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdIn(List<Integer> values) {
            addCriterion("mk_platform_menu.platform_menu_id in", values, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdNotIn(List<Integer> values) {
            addCriterion("mk_platform_menu.platform_menu_id not in", values, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_menu.platform_menu_id between", value1, value2, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andPlatformMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_menu.platform_menu_id not between", value1, value2, "platformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdIsNull() {
            addCriterion("mk_platform_menu.parent_platform_menu_id is null");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdIsNotNull() {
            addCriterion("mk_platform_menu.parent_platform_menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdEqualTo(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id =", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdNotEqualTo(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id <>", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdGreaterThan(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id >", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id >=", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdLessThan(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id <", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_menu.parent_platform_menu_id <=", value, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdIn(List<Integer> values) {
            addCriterion("mk_platform_menu.parent_platform_menu_id in", values, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdNotIn(List<Integer> values) {
            addCriterion("mk_platform_menu.parent_platform_menu_id not in", values, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_menu.parent_platform_menu_id between", value1, value2, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andParentPlatformMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_menu.parent_platform_menu_id not between", value1, value2, "parentPlatformMenuId");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("mk_platform_menu.menu_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("mk_platform_menu.menu_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_name =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_name <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("mk_platform_menu.menu_name >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_name >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("mk_platform_menu.menu_name <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_name <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("mk_platform_menu.menu_name like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("mk_platform_menu.menu_name not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_name in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_name not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_name between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_name not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNull() {
            addCriterion("mk_platform_menu.menu_url is null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNotNull() {
            addCriterion("mk_platform_menu.menu_url is not null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_url =", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_url <>", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThan(String value) {
            addCriterion("mk_platform_menu.menu_url >", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_url >=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThan(String value) {
            addCriterion("mk_platform_menu.menu_url <", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_url <=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLike(String value) {
            addCriterion("mk_platform_menu.menu_url like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotLike(String value) {
            addCriterion("mk_platform_menu.menu_url not like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_url in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_url not in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_url between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_url not between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuGradeIsNull() {
            addCriterion("mk_platform_menu.menu_grade is null");
            return (Criteria) this;
        }

        public Criteria andMenuGradeIsNotNull() {
            addCriterion("mk_platform_menu.menu_grade is not null");
            return (Criteria) this;
        }

        public Criteria andMenuGradeEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_grade =", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeNotEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_grade <>", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeGreaterThan(String value) {
            addCriterion("mk_platform_menu.menu_grade >", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_grade >=", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeLessThan(String value) {
            addCriterion("mk_platform_menu.menu_grade <", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_menu.menu_grade <=", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeLike(String value) {
            addCriterion("mk_platform_menu.menu_grade like", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeNotLike(String value) {
            addCriterion("mk_platform_menu.menu_grade not like", value, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_grade in", values, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeNotIn(List<String> values) {
            addCriterion("mk_platform_menu.menu_grade not in", values, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_grade between", value1, value2, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andMenuGradeNotBetween(String value1, String value2) {
            addCriterion("mk_platform_menu.menu_grade not between", value1, value2, "menuGrade");
            return (Criteria) this;
        }

        public Criteria andEqualTo(String field, Object value) {
            if (value == null) return andIsNull(field);
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            addCriterion(field+" = ", value, field);
            return (Criteria)this;
        }

        public Criteria andNotEqualTo(String field, Object value) {
            if (value == null) return andIsNotNull(field);
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            addCriterion(field+" <> ", value, field);
            return (Criteria)this;
        }

        public Criteria andIsNull(String field) {
            addCriterion(field+" is null");
            return (Criteria)this;
        }

        public Criteria andIsNotNull(String field) {
            addCriterion(field+" is not null");
            return (Criteria)this;
        }

        public Criteria and(String condition) {
            addCriterion(condition);
            return (Criteria)this;
        }

        private List<Integer> arrayOfIntToListOfInteger(int[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (int i : values) list.add(i);
            return list;
        }

        private List<Integer> arrayOfLongToListOfInteger(long[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (long i : values) if (i >= Integer.MIN_VALUE && i <= Integer.MAX_VALUE) list.add((int)i);
            return list;
        }

        private List<Integer> arrayOfNumberToListOfInteger(Number[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (Number i : values) if (i != null && i.longValue() >= Integer.MIN_VALUE && i.longValue() <= Integer.MAX_VALUE) list.add(i.intValue());
            return list;
        }

        private List<Integer> setOfNumberToListOfInteger(Set<? extends Number> values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (Number i : values) if (i != null && i.longValue() >= Integer.MIN_VALUE && i.longValue() <= Integer.MAX_VALUE) list.add(i.intValue());
            return list;
        }

        public Criteria andPlatformMenuIdIn(int[] values) {
            return andPlatformMenuIdIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdIn(long[] values) {
            return andPlatformMenuIdIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdIn(Number[] values) {
            return andPlatformMenuIdIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdIn(Set<? extends Number> values) {
            return andPlatformMenuIdIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdNotIn(int[] values) {
            return andPlatformMenuIdNotIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdNotIn(long[] values) {
            return andPlatformMenuIdNotIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdNotIn(Number[] values) {
            return andPlatformMenuIdNotIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformMenuIdNotIn(Set<? extends Number> values) {
            return andPlatformMenuIdNotIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdIn(int[] values) {
            return andParentPlatformMenuIdIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdIn(long[] values) {
            return andParentPlatformMenuIdIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdIn(Number[] values) {
            return andParentPlatformMenuIdIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdIn(Set<? extends Number> values) {
            return andParentPlatformMenuIdIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdNotIn(int[] values) {
            return andParentPlatformMenuIdNotIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdNotIn(long[] values) {
            return andParentPlatformMenuIdNotIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdNotIn(Number[] values) {
            return andParentPlatformMenuIdNotIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andParentPlatformMenuIdNotIn(Set<? extends Number> values) {
            return andParentPlatformMenuIdNotIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andIf(String field, String operator, Object value) {
            return andIf(field, operator, value, null, null);
        }

        public Criteria andIf(String field, String operator, Object value, String beforeValue, String afterValue) {
            if (field == null || field.trim().length() == 0) { field = "null"; }
            if (operator == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".operator */ "); return (Criteria)this; }
            if (value == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".value */ "); return (Criteria)this; }
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            String condition = field + " "+operator+" ";
            Criterion c = new Criterion(condition, value);
            if (beforeValue != null) c.beforeValue = beforeValue;
            if (afterValue != null) c.afterValue = afterValue;
            criteria.add(c);
            return (Criteria)this;
        }

        public Criteria andRightIf(Object value, String operator, String field) {
            return andRightIf(value, operator, field, null, null);
        }

        public Criteria andRightIf(Object value, String operator, String field, String beforeValue, String afterValue) {
            if (field == null || field.trim().length() == 0) { field = "null"; }
            if (operator == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".operator */ "); return (Criteria)this; }
            if (value == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".value */ "); return (Criteria)this; }
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            String condition = " "+operator+" "+field;
            Criterion c = new Criterion(condition, value);
            if (beforeValue != null) c.beforeValue = beforeValue;
            if (afterValue != null) c.afterValue = afterValue;
            c.rightValue = true;
            criteria.add(c);
            return (Criteria)this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        private String afterValue = "";

        private String beforeValue = "";

        private boolean rightValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getAfterValue() {
            return afterValue;
        }

        public String getBeforeValue() {
            return beforeValue;
        }

        public boolean isRightValue() {
            return rightValue;
        }
    }
}