package com.mkstore.mk.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class MkPlatformJurisdictionExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by JoinPlugin
     * Name of the database table represented by this class
     */
    public static final String TABLE = "mk_platform_jurisdiction";

    /**
     * This field was generated by JoinPlugin
     * SQL query alias of the database table represented by this class
     */
    public static final String ALIAS = "mk_platform_jurisdiction";

    /**
     * This field was generated by JoinPlugin
     * SQL query alias of the database table represented by this class
     */
    public static final String ALIAS_ = "mk_platform_jurisdiction.";

    private List<String> from;

    private Integer limit;

    private Integer offset;

    public MkPlatformJurisdictionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        from = null;
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public List<String> getFrom() {
        return from;
    }

    public MkPlatformJurisdictionExample addFromClause(String join) {
        if (join == null || (join = join.trim()).length() == 0) return this;
        if (from == null) from = new java.util.ArrayList<String>();
        from.add(join);
        return this;
    }

    /**
     * @param formatString A {@link java.util.Formatter format string} for join expression
     * @param firstArg First argument referenced by the format specifiers in the format string
     * @param secondAndFurtherArgs Second and further arguments referenced by the format specifiers in the format string
     */
    public MkPlatformJurisdictionExample addFromClause(String formatString, Object firstArg, Object ... secondAndFurtherArgs) {
        if (formatString == null || (formatString = formatString.trim()).length() == 0) return this;
        if (from == null) from = new java.util.ArrayList<String>();
        Object[] temp = new Object[(secondAndFurtherArgs == null ? 0 : secondAndFurtherArgs.length) + 1];
        if (secondAndFurtherArgs != null) System.arraycopy(secondAndFurtherArgs, 0, temp, 1, secondAndFurtherArgs.length);
        temp[0] = firstArg;
        String formatted = String.format(formatString, temp);
        from.add(formatted);
        return this;
    }

    public Integer getLimit() {
        return limit;
    }

    public Integer getOffset() {
        return offset;
    }

    public MkPlatformJurisdictionExample setLimitAndOffset(Integer limit, Integer offset) {
        if (limit != null && limit > 0) {
            this.limit = limit;
            this.offset = (offset != null && offset > 0) ? offset : null;
        } else {
            this.limit = this.offset = null;
        }
        return this;
    }

    public MkPlatformJurisdictionExample setLimit(Integer limit) {
        return setLimitAndOffset(limit, null);
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlatformJurisdictionIdIsNull() {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdIsNotNull() {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id =", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdNotEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id <>", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdGreaterThan(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id >", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id >=", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdLessThan(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id <", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdLessThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id <=", value, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdIn(List<Integer> values) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id in", values, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdNotIn(List<Integer> values) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id not in", values, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id between", value1, value2, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andPlatformJurisdictionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_jurisdiction.platform_jurisdiction_id not between", value1, value2, "platformJurisdictionId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("mk_platform_jurisdiction.menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("mk_platform_jurisdiction.menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("mk_platform_jurisdiction.menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Integer> values) {
            addCriterion("mk_platform_jurisdiction.menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Integer> values) {
            addCriterion("mk_platform_jurisdiction.menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_jurisdiction.menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mk_platform_jurisdiction.menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIsNull() {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name is null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIsNotNull() {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name is not null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name =", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name <>", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameGreaterThan(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name >", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name >=", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLessThan(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name <", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name <=", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLike(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name like", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotLike(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name not like", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name in", values, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name not in", values, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name between", value1, value2, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_name not between", value1, value2, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlIsNull() {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url is null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlIsNotNull() {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url is not null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url =", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlNotEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url <>", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlGreaterThan(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url >", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url >=", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlLessThan(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url <", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url <=", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlLike(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url like", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlNotLike(String value) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url not like", value, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url in", values, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlNotIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url not in", values, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url between", value1, value2, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andJurisdictionUrlNotBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.jurisdiction_url not between", value1, value2, "jurisdictionUrl");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("mk_platform_jurisdiction.item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("mk_platform_jurisdiction.item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("mk_platform_jurisdiction.item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("mk_platform_jurisdiction.item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("mk_platform_jurisdiction.item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("mk_platform_jurisdiction.item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("mk_platform_jurisdiction.item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("mk_platform_jurisdiction.item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("mk_platform_jurisdiction.item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andEqualTo(String field, Object value) {
            if (value == null) return andIsNull(field);
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            addCriterion(field+" = ", value, field);
            return (Criteria)this;
        }

        public Criteria andNotEqualTo(String field, Object value) {
            if (value == null) return andIsNotNull(field);
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            addCriterion(field+" <> ", value, field);
            return (Criteria)this;
        }

        public Criteria andIsNull(String field) {
            addCriterion(field+" is null");
            return (Criteria)this;
        }

        public Criteria andIsNotNull(String field) {
            addCriterion(field+" is not null");
            return (Criteria)this;
        }

        public Criteria and(String condition) {
            addCriterion(condition);
            return (Criteria)this;
        }

        private List<Integer> arrayOfIntToListOfInteger(int[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (int i : values) list.add(i);
            return list;
        }

        private List<Integer> arrayOfLongToListOfInteger(long[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (long i : values) if (i >= Integer.MIN_VALUE && i <= Integer.MAX_VALUE) list.add((int)i);
            return list;
        }

        private List<Integer> arrayOfNumberToListOfInteger(Number[] values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (Number i : values) if (i != null && i.longValue() >= Integer.MIN_VALUE && i.longValue() <= Integer.MAX_VALUE) list.add(i.intValue());
            return list;
        }

        private List<Integer> setOfNumberToListOfInteger(Set<? extends Number> values) {
            List<Integer> list = new ArrayList<Integer>();
            if (values != null) for (Number i : values) if (i != null && i.longValue() >= Integer.MIN_VALUE && i.longValue() <= Integer.MAX_VALUE) list.add(i.intValue());
            return list;
        }

        public Criteria andPlatformJurisdictionIdIn(int[] values) {
            return andPlatformJurisdictionIdIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdIn(long[] values) {
            return andPlatformJurisdictionIdIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdIn(Number[] values) {
            return andPlatformJurisdictionIdIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdIn(Set<? extends Number> values) {
            return andPlatformJurisdictionIdIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdNotIn(int[] values) {
            return andPlatformJurisdictionIdNotIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdNotIn(long[] values) {
            return andPlatformJurisdictionIdNotIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdNotIn(Number[] values) {
            return andPlatformJurisdictionIdNotIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andPlatformJurisdictionIdNotIn(Set<? extends Number> values) {
            return andPlatformJurisdictionIdNotIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andMenuIdIn(int[] values) {
            return andMenuIdIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andMenuIdIn(long[] values) {
            return andMenuIdIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andMenuIdIn(Number[] values) {
            return andMenuIdIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andMenuIdIn(Set<? extends Number> values) {
            return andMenuIdIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andMenuIdNotIn(int[] values) {
            return andMenuIdNotIn(arrayOfIntToListOfInteger(values));
        }

        public Criteria andMenuIdNotIn(long[] values) {
            return andMenuIdNotIn(arrayOfLongToListOfInteger(values));
        }

        public Criteria andMenuIdNotIn(Number[] values) {
            return andMenuIdNotIn(arrayOfNumberToListOfInteger(values));
        }

        public Criteria andMenuIdNotIn(Set<? extends Number> values) {
            return andMenuIdNotIn(setOfNumberToListOfInteger(values));
        }

        public Criteria andIf(String field, String operator, Object value) {
            return andIf(field, operator, value, null, null);
        }

        public Criteria andIf(String field, String operator, Object value, String beforeValue, String afterValue) {
            if (field == null || field.trim().length() == 0) { field = "null"; }
            if (operator == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".operator */ "); return (Criteria)this; }
            if (value == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".value */ "); return (Criteria)this; }
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            String condition = field + " "+operator+" ";
            Criterion c = new Criterion(condition, value);
            if (beforeValue != null) c.beforeValue = beforeValue;
            if (afterValue != null) c.afterValue = afterValue;
            criteria.add(c);
            return (Criteria)this;
        }

        public Criteria andRightIf(Object value, String operator, String field) {
            return andRightIf(value, operator, field, null, null);
        }

        public Criteria andRightIf(Object value, String operator, String field, String beforeValue, String afterValue) {
            if (field == null || field.trim().length() == 0) { field = "null"; }
            if (operator == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".operator */ "); return (Criteria)this; }
            if (value == null) { addCriterion("1=2 /* "+field.replaceAll("[^0-9A-Za-z _.()]","")+".value */ "); return (Criteria)this; }
            if (value instanceof java.util.Date) value = new java.sql.Date(((java.util.Date)value).getTime());
            String condition = " "+operator+" "+field;
            Criterion c = new Criterion(condition, value);
            if (beforeValue != null) c.beforeValue = beforeValue;
            if (afterValue != null) c.afterValue = afterValue;
            c.rightValue = true;
            criteria.add(c);
            return (Criteria)this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        private String afterValue = "";

        private String beforeValue = "";

        private boolean rightValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getAfterValue() {
            return afterValue;
        }

        public String getBeforeValue() {
            return beforeValue;
        }

        public boolean isRightValue() {
            return rightValue;
        }
    }
}